!function o(l, n, s) { function a(t, e) { if (!n[t]) { if (!l[t]) { var r = "function" == typeof require && require; if (!e && r) return r(t, !0); if (i) return i(t, !0); throw (r = new Error("Cannot find module '" + t + "'")).code = "MODULE_NOT_FOUND", r } r = n[t] = { exports: {} }, l[t][0].call(r.exports, function (e) { return a(l[t][1][e] || e) }, r, r.exports, o, l, n, s) } return n[t].exports } for (var i = "function" == typeof require && require, e = 0; e < s.length; e++)a(s[e]); return a }({ 1: [function (e, t, r) { "use strict"; var o = e("@babel/runtime/helpers/interopRequireDefault"), l = o(e("@babel/runtime/helpers/classCallCheck")), n = o(e("@babel/runtime/helpers/classPrivateFieldGet")), s = new WeakMap, a = new WeakMap, i = new WeakMap; new function e() { var o = this; (0, l.default)(this, e), s.set(this, { writable: !0, value: { thumbsVerticalLayout: document.querySelector(".owp-thumbs-layout-vertical") } }), a.set(this, { writable: !0, value: function () { window.addEventListener("load", (0, n.default)(o, i)), window.addEventListener("resize", (0, n.default)(o, i)) } }), i.set(this, { writable: !0, value: function () { var e, t, r = (0, n.default)(o, s).thumbsVerticalLayout.querySelector(".flex-control-nav"); r && (768 < window.innerWidth ? (t = null === (e = (0, n.default)(o, s).thumbsVerticalLayout.querySelector(".flex-viewport")) || void 0 === e ? void 0 : e.offsetHeight) + 50 < (null === (e = (0, n.default)(o, s).thumbsVerticalLayout.querySelector(".flex-control-nav")) || void 0 === e ? void 0 : e.offsetHeight) && (r.style.maxHeight = "".concat(t, "px")) : r.style.maxHeight = "") } }), (0, n.default)(this, s).thumbsVerticalLayout && (0, n.default)(this, a).call(this) } }, { "@babel/runtime/helpers/classCallCheck": 3, "@babel/runtime/helpers/classPrivateFieldGet": 5, "@babel/runtime/helpers/interopRequireDefault": 6 }], 2: [function (e, t, r) { t.exports = function (e, t) { return t.get ? t.get.call(e) : t.value }, t.exports.default = t.exports, t.exports.__esModule = !0 }, {}], 3: [function (e, t, r) { t.exports = function (e, t) { if (!(e instanceof t)) throw new TypeError("Cannot call a class as a function") }, t.exports.default = t.exports, t.exports.__esModule = !0 }, {}], 4: [function (e, t, r) { t.exports = function (e, t, r) { if (!t.has(e)) throw new TypeError("attempted to " + r + " private field on non-instance"); return t.get(e) }, t.exports.default = t.exports, t.exports.__esModule = !0 }, {}], 5: [function (e, t, r) { var o = e("./classApplyDescriptorGet.js"), l = e("./classExtractFieldDescriptor.js"); t.exports = function (e, t) { return t = l(e, t, "get"), o(e, t) }, t.exports.default = t.exports, t.exports.__esModule = !0 }, { "./classApplyDescriptorGet.js": 2, "./classExtractFieldDescriptor.js": 4 }], 6: [function (e, t, r) { t.exports = function (e) { return e && e.__esModule ? e : { default: e } }, t.exports.default = t.exports, t.exports.__esModule = !0 }, {}] }, {}, [1]);

/*  */


/*!
	Zoom 1.7.21
	license: MIT
	http://www.jacklmoore.com/zoom
*/
!function(o){var t={url:!1,callback:!1,target:!1,duration:120,on:"mouseover",touch:!0,onZoomIn:!1,onZoomOut:!1,magnify:1};o.zoom=function(t,e,n,i){var u,a,c,r,l,m,f,s=o(t),h=s.css("position"),d=o(e);return t.style.position=/(absolute|fixed)/.test(h)?h:"relative",t.style.overflow="hidden",n.style.width=n.style.height="",o(n).addClass("zoomImg").css({position:"absolute",top:0,left:0,opacity:0,width:n.width*i,height:n.height*i,border:"none",maxWidth:"none",maxHeight:"none"}).appendTo(t),{init:function(){a=s.outerWidth(),u=s.outerHeight(),e===t?(r=a,c=u):(r=d.outerWidth(),c=d.outerHeight()),l=(n.width-a)/r,m=(n.height-u)/c,f=d.offset()},move:function(o){var t=o.pageX-f.left,e=o.pageY-f.top;e=Math.max(Math.min(e,c),0),t=Math.max(Math.min(t,r),0),n.style.left=t*-l+"px",n.style.top=e*-m+"px"}}},o.fn.zoom=function(e){return this.each(function(){var n=o.extend({},t,e||{}),i=n.target&&o(n.target)[0]||this,u=this,a=o(u),c=document.createElement("img"),r=o(c),l="mousemove.zoom",m=!1,f=!1;if(!n.url){var s=u.querySelector("img");if(s&&(n.url=s.getAttribute("data-src")||s.currentSrc||s.src,n.alt=s.getAttribute("data-alt")||s.alt),!n.url)return}a.one("zoom.destroy",function(o,t){a.off(".zoom"),i.style.position=o,i.style.overflow=t,c.onload=null,r.remove()}.bind(this,i.style.position,i.style.overflow)),c.onload=function(){var t=o.zoom(i,u,c,n.magnify);function e(e){t.init(),t.move(e),r.stop().fadeTo(o.support.opacity?n.duration:0,1,"function"==typeof n.onZoomIn&&n.onZoomIn.call(c))}function s(){r.stop().fadeTo(n.duration,0,"function"==typeof n.onZoomOut&&n.onZoomOut.call(c))}"grab"===n.on?a.on("mousedown.zoom",function(n){1===n.which&&(o(document).one("mouseup.zoom",function(){s(),o(document).off(l,t.move)}),e(n),o(document).on(l,t.move),n.preventDefault())}):"click"===n.on?a.on("click.zoom",function(n){return m?void 0:(m=!0,e(n),o(document).on(l,t.move),o(document).one("click.zoom",function(){s(),m=!1,o(document).off(l,t.move)}),!1)}):"toggle"===n.on?a.on("click.zoom",function(o){m?s():e(o),m=!m}):"mouseover"===n.on&&(t.init(),a.on("mouseenter.zoom",e).on("mouseleave.zoom",s).on(l,t.move)),n.touch&&a.on("touchstart.zoom",function(o){o.preventDefault(),f?(f=!1,s()):(f=!0,e(o.originalEvent.touches[0]||o.originalEvent.changedTouches[0]))}).on("touchmove.zoom",function(o){o.preventDefault(),t.move(o.originalEvent.touches[0]||o.originalEvent.changedTouches[0])}).on("touchend.zoom",function(o){o.preventDefault(),f&&(f=!1,s())}),"function"==typeof n.callback&&n.callback.call(c)},c.setAttribute("role","presentation"),c.alt=n.alt||"",c.src=n.url})},o.fn.zoom.defaults=t}(window.jQuery);



Propulsez la réputation en ligne de votre entreprise avec notre Plaque QR Code + NFC dédiée à la collecte rapide et pratique d'avis Google. Cette solution intelligente allie la simplicité du code QR à la technologie NFC, offrant une expérience client sans effort pour recueillir des retours authentiques.

Caractéristiques Clés :

Avis Google en Un Clic :
Transformez la collecte d'avis Google en une expérience instantanée. Les clients peuvent scanner le QR code ou utiliser la technologie NFC pour accéder directement à la page d'avis Google de votre entreprise.
Compatibilité Universelle :
Fonctionne avec tous les smartphones équipés de caméras pour la lecture du QR code et prend en charge les dispositifs NFC, assurant une accessibilité maximale.
Installation Polyvalente :
Facile à installer sur des murs, comptoirs ou toute surface visible. Intégrez-la harmonieusement à votre espace pour une visibilité optimale.
Sécurité des Données Garantie :
Conforme aux normes de sécurité des données, cette plaque assure la confidentialité des avis collectés, renforçant ainsi la confiance de vos clients.
Gestion Simplifiée des Avis :
Accédez à une interface de gestion conviviale pour suivre, répondre et tirer des enseignements des avis collectés. Transformez chaque retour en opportunité d'amélioration.

Avantages Uniques :

Gain de Notoriété Google : Obtenez des avis positifs sur Google pour renforcer votre présence en ligne.
Interaction Instantanée : Offrez à vos clients une méthode rapide pour partager leurs expériences.
Réputation Solide : Bâtissez une réputation solide avec des avis authentiques provenant directement de votre clientèle.

Optimisez votre présence en ligne avec notre Plaque QR Code + NFC dédiée aux avis Google. Simplifiez la collecte d'avis pour vos clients tout en renforçant la crédibilité et la visibilité de votre entreprise sur la plateforme la plus influente.